# Generated by Django 2.1.2 on 2018-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('addressee', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('duration_call', models.CharField(max_length=255)),
                ('origin_number', models.CharField(max_length=255)),
                ('audio', models.CharField(max_length=255)),
                ('convert_to_text', models.TextField()),
            ],
            options={
                'db_table': 'calls',
            },
        ),
    ]
