# Generated by Django 2.1.2 on 2018-12-12 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20181207_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='prediction',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='calldate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 12, 9, 46, 9, 240124)),
        ),
    ]
