# Generated by Django 2.1.2 on 2018-12-12 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_auto_20181212_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='calldate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 12, 10, 15, 28, 64723)),
        ),
        migrations.AlterField(
            model_name='calls',
            name='prediction',
            field=models.TextField(null=True),
        ),
    ]
