# Generated by Django 2.1.2 on 2018-12-12 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_auto_20181212_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='audio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='calldate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 12, 13, 44, 38, 368559)),
        ),
        migrations.AlterField(
            model_name='calls',
            name='convert_to_text',
            field=models.TextField(null=True),
        ),
    ]
