# Generated by Django 2.1.2 on 2018-12-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_auto_20181212_1344'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE calls CHANGE `calldate` `calldate` DATETIME NOT NULL;"
        )
    ]
