# Generated by Django 2.1.2 on 2018-11-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('cliente', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
                ('audio1', models.CharField(max_length=255)),
                ('conversion_audio1', models.CharField(max_length=255)),
                ('audio2', models.CharField(max_length=255)),
                ('conversion_audio2', models.CharField(max_length=255)),
                ('flag_converted', models.BooleanField()),
            ],
            options={
                'db_table': 'experience',
            },
        ),
    ]
