# Generated by Django 2.1.2 on 2018-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
