# Generated by Django 2.1.2 on 2018-11-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_auto_20181103_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='conversion_audio1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='conversion_audio2',
            field=models.TextField(),
        ),
    ]
