# Generated by Django 2.1.2 on 2018-11-06 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20181105_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
