# Generated by Django 2.1.2 on 2018-11-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_auto_20181125_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='audio1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='audio2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='conversion_audio1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='pediste_info',
            field=models.BooleanField(null=True),
        ),
    ]
