# Generated by Django 2.1.2 on 2018-12-12 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0009_auto_20181127_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='expedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 12, 9, 46, 9, 234124)),
        ),
        migrations.AddField(
            model_name='experience',
            name='prediction',
            field=models.DateTimeField(null=True),
        ),
    ]
