# Generated by Django 2.1.2 on 2018-12-12 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0011_auto_20181212_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='expedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 12, 13, 44, 38, 344558)),
        ),
    ]
