# Generated by Django 2.1.2 on 2018-12-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0012_auto_20181212_1344'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE experience CHANGE `expedate` `expedate` DATETIME NOT NULL;"
        )
    ]
