# Generated by Django 2.1.2 on 2018-12-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0013_auto_20181213_1610'),
    ]

    operations = [
    ]
